let route = [
    {
        title:'首页',
        route:'/',
        page:'/index.html'
    },
    {
        title:'首页',
        route:'/index',
        page:'/index.html'
    },
    {
        title:'关于我们',
        route:'/aboutus',
        page:'/aboutus.html'
    },
    {
        title:'产品中心',
        route:'/product',
        page:'/product.html'
    },
    {
        title:'产品中心详情',
        route:'/productDetails',
        page:'/productDetails.html'
    },
    {
        title:'案例中心',
        route:'/case',
        page:'/case.html'
    },
    {
        title:'新闻中心',
        route:'/news',
        page:'/news.html'
    },
    {
        title:'新闻详情',
        route:'/newsDetails',
        page:'/newsDetails.html'
    },
    {
        title:'加盟我们',
        route:'/join',
        page:'/join.html'
    }
];
module.exports = route;