let route = [
    {
        title:'首页',
        route:'/',
        page:'/index.html'
    },
    {
        title:'首页',
        route:'/index',
        page:'/index.html'
    },
    {
        title:'作品',
        route:'/product',
        page:'/product.html'
    },
    {
        title:'研究',
        route:'/study',
        page:'/study.html'
    },
    {
        title:'作品列表',
        route:'/productList',
        page:'/productList.html'
    },
    {
        title:'作品详情',
        route:'/productDetail',
        page:'/productDetail.html'
    },
    {
        title:'新闻中心',
        route:'/news',
        page:'/news.html'
    },
    {
        title:'新闻详情',
        route:'/newsDetails',
        page:'/newsDetails.html'
    },
    {
        title:'加盟我们',
        route:'/join',
        page:'/join.html'
    }
];
module.exports = route;